project:
  type: website

website:
  title: "Mateo Jacques"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      - href: example_analysis.qmd
        text: Example Analysis

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

bibliography: references.bib
csl: apa.csl
